opentok/one-to-one-screen-annotations-sample-apps

ios/OneToOneScreenShareSample/OneToOneScreenShareSample.xcodeproj/project.pbxproj
ios/OneToOneScreenShareSample/OneToOneScreenShareSample/AppDelegate.h
ios/OneToOneScreenShareSample/OneToOneScreenShareSample/AppDelegate.m
ios/OneToOneScreenShareSample/OneToOneScreenShareSample/Info.plist
ios/OneToOneScreenShareSample/OneToOneScreenShareSample/MainView.h
ios/OneToOneScreenShareSample/OneToOneScreenShareSample/MainView.m
ios/OneToOneScreenShareSample/OneToOneScreenShareSample/MainViewController.h
ios/OneToOneScreenShareSample/OneToOneScreenShareSample/MainViewController.m
ios/OneToOneScreenShareSample/OneToOneScreenShareSample/main.m

//cc @Lucashuang0802 @marinaserranomontes @marko07

changing project bundle id and changing the header in the one to one sample project

---

ios/ScreenShareAccPackKit/OTScreenShareKit/ScreenShare/OTScreenSharer.m

//cc @Lucashuang0802 @marinaserranomontes @marko07

adding logger to ScreenShare

---

android/build.sh

@marinaserranomontes please merge :)

Adding android build.sh

---

JS/README.md

DOC-40: revisions based on review session with @adrice727

DOC-40: reivisions based on review session with @adrice727

---

android/OneToOneScreenSharingSample/app/build.gradle
android/ScreensharingAccPackKit/screensharing-acc-pack-kit/build.gradle

Fixing deps versions

---

android/OneToOneScreenSharingSample/app/src/main/java/com/tokbox/android/screensharingsample/config/OpenTokConfig.java
android/ScreensharingAccPackKit/screensharing-acc-pack-kit/src/main/java/com/tokbox/android/accpack/screensharing/config/OpenTokConfig.java

Updating android versions

---

android/ScreensharingAccPackKit/screensharing-acc-pack-kit/build.gradle

Fix android build

---

android/OneToOneScreenSharingSample/app/src/main/java/com/tokbox/android/screensharingsample/MainActivity.java
android/OneToOneScreenSharingSample/app/src/main/java/com/tokbox/android/screensharingsample/config/OpenTokConfig.java
android/ScreensharingAccPackKit/screensharing-acc-pack-kit/src/main/java/com/tokbox/android/accpack/screensharing/ScreenSharingFragment.java
android/ScreensharingAccPackKit/screensharing-acc-pack-kit/src/main/java/com/tokbox/android/accpack/screensharing/config/OpenTokConfig.java

Adding subscriber annotations for screensharing 

---

android/OneToOneScreenSharingSample/app/build.gradle
android/OneToOneScreenSharingSample/app/src/main/java/com/tokbox/android/screensharingsample/MainActivity.java
android/ScreensharingAccPackKit/gradle.properties
android/ScreensharingAccPackKit/screensharing-acc-pack-kit/build.gradle
android/ScreensharingAccPackKit/screensharing-acc-pack-kit/src/main/java/com/tokbox/android/accpack/screensharing/ScreenSharingFragment.java

Fixing android

---

ios/OneToOneScreenShareSample/OneToOneScreenShareSample/MainView.m
ios/OneToOneScreenShareSample/OneToOneScreenShareSample/MainViewController.m
ios/OneToOneScreenShareSample/Podfile

Adjusting a little the clearCanvas, the shareInstance and the Pod
thanks @Lucashuang0802

quick fix for the sharedInstance

---

android/OneToOneScreenSharingSample/app/src/main/java/com/tokbox/android/screensharingsample/MainActivity.java
android/OneToOneScreenSharingSample/app/src/main/java/com/tokbox/android/screensharingsample/config/OpenTokConfig.java
android/OneToOneScreenSharingSample/app/src/main/java/com/tokbox/android/screensharingsample/ui/PreviewControlFragment.java
android/OneToOneScreenSharingSample/app/src/main/res/drawable/bckg_icon_selected.xml
android/OneToOneScreenSharingSample/app/src/main/res/layout/preview_actionbar_fragment.xml
android/ScreensharingAccPackKit/screensharing-acc-pack-kit/src/main/java/com/tokbox/android/accpack/screensharing/ScreenSharingFragment.java
android/ScreensharingAccPackKit/screensharing-acc-pack-kit/src/main/res/layout/content_layout.xml

Fixing remote annotations

---

android/OneToOneScreenSharingSample/app/src/main/java/com/tokbox/android/screensharingsample/config/OpenTokConfig.java

Removing android credentials

---

android/README.md

revised android content per Marina review

OTS-283: revised per Marina review

---

android/OneToOneScreenSharingSample/app/src/main/java/com/tokbox/android/screensharingsample/MainActivity.java
android/OneToOneScreenSharingSample/app/src/main/res/layout/activity_main.xml

Fixing annotations toolbar behaviour

---

android/OneToOneScreenSharingSample/app/src/main/java/com/tokbox/android/screensharingsample/MainActivity.java

Fixing background behaviour

---

JS/opentok.js-ss-annotation/src/acc-pack-screen-sharing.js

appending control before last button

---

android/OneToOneScreenSharingSample/app/build.gradle
android/OneToOneScreenSharingSample/app/src/main/java/com/tokbox/android/screensharingsample/config/OpenTokConfig.java
android/README.md

Updating android version to 1.1.0

---

ios/README.md

Updating iOS version

---

JS/README.md
JS/opentok.js-ss-annotation/gulpfile.js
README.md

Updaging js version

---

android/README.md

Fixing android doc

---

android/OneToOneScreenSharingSample/app/src/main/java/com/tokbox/android/screensharingsample/MainActivity.java
android/OneToOneScreenSharingSample/app/src/main/java/com/tokbox/android/screensharingsample/ui/PreviewControlFragment.java

Fixing android sample when screensharing view is closed

---

android/README.md

Android doc refactoring

---

android/OneToOneScreenSharingSample/app/build.gradle
android/OneToOneScreenSharingSample/app/src/main/AndroidManifest.xml
android/OneToOneScreenSharingSample/app/src/main/java/com/tokbox/android/screensharingsample/MainActivity.java
android/OneToOneScreenSharingSample/build.gradle

Screenshot fixes and update to SDK target 24

---

android/OneToOneScreenSharingSampleUITests/ScreenSharingUITest.py
android/build.sh
ios/OneToOneScreenShareSampleUITests/ScreenShareUITest.py
ios/test.sh

@marinaserranomontes @Lucashuang0802 please merge :)

Adding UI tests for mobile
